[build]
  command = "npm run build"  # Your build command for Astro
  publish = "dist"  # The directory where your built site is located

[forms]
  # This enables form processing
  submissions = true
